name: Docker Build by tagging

on:
  create:
    tags:
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get tag name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract name from package.json
        uses: sergeysova/jq-action@v2
        id: name
        with:
          cmd: 'jq .name package.json -r'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: lambda256/${{ steps.name.outputs.value }}_${{ env.TAG }}
          build-args: |
            "PAT=${{ secrets.PA_TOKEN_LUNIVERSEDEVOPS }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "image": "lambda256/${{ steps.name.outputs.value }}_${{ env.TAG }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
