name: Migrate luniverse-dev database by comment '/migrate dev'

on:
  issue_comment:
    types: [ created ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ startsWith(github.event.comment.body, '/migrate dev') }}

    runs-on: arc-runner-set-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Extract arguments from comment
        run: |
          ARGS=$(echo "${{ github.event.comment.body }}" | cut -d' ' -f3-)
          IFS=' ' read -r DB_HOST DB_PORT DB_DATABASE <<< "$ARGS"
          DB_HOST=${DB_HOST:-${{ vars.DB_HOST }}}
          DB_PORT=${DB_PORT:-${{ vars.DB_PORT }}}
          DB_DATABASE=${DB_DATABASE:-${{ vars.DB_DATABASE }}}
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
          echo "DB_DATABASE=$DB_DATABASE" >> $GITHUB_ENV

      - name: Install git and Configure git to use HTTPS instead of SSH
        run: |
          if ! command -v git &> /dev/null
          then
            echo "Git could not be found, installing Git..."
            sudo apt-get update
            sudo apt-get install -y git
          fi
          git config --global url."https://${{secrets.PA_TOKEN_LUNIVERSEDEVOPS}}@github.com/".insteadOf ssh://git@github.com/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 필요에 따라 Node.js 버전 조정

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --include=dev

      - name: Run migrations
        run: npm run migrate:run
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ vars.DB_DEV_MIGRATION_DBA_USERNAME }}
          DB_CREDENTIAL: ${{ secrets.DB_DEV_MIGRATION_DBA_CREDENTIAL }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({            
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Migrate luniverse-dev db successfully'
            })
